using System.Xml.Serialization;

/*@author Irena Bojanova(ivb)
 *@date - 2/9/2022 */

namespace BFCVEDB
{
    public class CVE
    {
        //xxxx
        string GenTool = "Generated by the BFCVE tool.";

        [XmlAttribute] public string Name { get; set; } = string.Empty;
        [XmlElement] public Weakness BugWeakness { get; set; } = new();
        [XmlElement ("Weakness")] public Weakness[]? Weaknesses { get; set; }
        [XmlElement] public Weakness WeaknessFailure { get; set; } = new();

        public override string ToString() => 
            @$"{GenTool}{Environment.NewLine}{Name}:{BugWeakness}{Environment.NewLine}{string.Concat(Weaknesses?.Select(w => Environment.NewLine + w.ToString()) ?? Enumerable.Empty<string>())}{Environment.NewLine}{WeaknessFailure}";
    }
}
